baseURL = "https://www.vereda.tec.br/"
title = "Vereda Tecnologia"
pluralizelisttitles = false
removepathaccents = true
paginatePath = "p"
defaultContentLanguage = "pt"

[params]
custom_css = ["css/style.css"]
sidebar = true
submitted = true
logoPath = "ipe-amarelo.png"
themeColor = "#da8020"

[languages.en]
weight = 2
languageName = "English"
languageCode = "en-us"

[languages.pt]
weight = 1
languageName = "Português"
languageCode = "pt-br"

